"""
RoboPulse Fleet Command Center
Day 3 - async database engine and session factory for the ORM models to use.

DATABASE_URL is read from an environment variable so today's demo
can point at a throwaway scratch database without editing this 
file - with hardcoded fallback for convenience. This is a known,
deliberate shortcut and we will replace this with a proper .env file
and a Pydantic settings class in a future demo. In a real project, 
don't commit a password here, it is not secure.
"""

import os

from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker, create_async_engine

#setting the database URL to an environment variable so that it can be easily 
# changed without modifying the code. If the environment variable is not set,
# it falls back to a default value for development purposes.
DATABASE_URL = os.environ.get(
    "DATABASE_URL",
    #put your own database url here with your password between postgres: and @localhost, 
    # e.g. postgresql+asyncpg://postgres:mysecretpassword@localhost:5432/robopulse_dev
    "postgresql+asyncpg://postgres:@localhost:5432/robopulse_dev",
)

#echo=True enables logging of all SQL statements generated by SQLAlchemy, 
# which is useful for debugging and understanding the database interactions.
engine = create_async_engine(DATABASE_URL, echo=True)

#expire_on_commit=False prevents the session from expiring objects after a commit,
AsyncSessionLocal = async_sessionmaker(engine, expire_on_commit=False)